import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatWeekRange } from '../utils/dateHelpers';

/**
 * PDF Generation Service
 * Creates printable PDFs for meal plans and grocery lists
 */

/**
 * Generate Meal Plan PDF
 */
export function generateMealPlanPDF(mealPlan, options = {}) {
  const { weekStartDate, days, totalCost, budget } = mealPlan;
  const { peopleCount = 2 } = options;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Weekly Meal Plan', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Week of ${formatWeekRange(weekStartDate)}`, pageWidth / 2, 28, { align: 'center' });
  doc.text(`For ${peopleCount} people`, pageWidth / 2, 35, { align: 'center' });

  // Budget info
  doc.setFontSize(10);
  const budgetStatus = totalCost <= budget ? '✓' : '!';
  doc.text(`${budgetStatus} Budget: $${totalCost.toFixed(2)} / $${budget.toFixed(2)}`, 20, 45);

  // Days table
  const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  const tableData = days.map(day => {
    const dayName = dayNames[day.day_of_week];
    let mealName = '';

    if (day.is_order_out_night) {
      mealName = '🍕 Order Out / Eat Out';
    } else if (day.is_leftover_night) {
      mealName = '🍱 Leftovers';
    } else if (day.recipe) {
      mealName = day.recipe.name;
    } else {
      mealName = 'No meal planned';
    }

    const cost = day.recipe?.total_cost ? `$${day.recipe.total_cost.toFixed(2)}` : '-';
    const status = day.status === 'completed' ? '✓' : day.status === 'shopped' ? '🛒' : '○';

    return [status, dayName, mealName, cost];
  });

  doc.autoTable({
    startY: 50,
    head: [['', 'Day', 'Meal', 'Cost']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [34, 139, 34], fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 30, fontStyle: 'bold' },
      2: { cellWidth: 110 },
      3: { cellWidth: 25, halign: 'right' }
    },
    styles: {
      fontSize: 10,
      cellPadding: 5
    }
  });

  // Recipe details (on new page if needed)
  let yPos = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Recipe Details', 20, yPos);
  yPos += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');

  days.forEach(day => {
    if (day.recipe && !day.is_leftover_night && !day.is_order_out_night) {
      // Check if we need a new page
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFont('helvetica', 'bold');
      doc.text(`${dayNames[day.day_of_week]}: ${day.recipe.name}`, 20, yPos);
      yPos += 5;

      doc.setFont('helvetica', 'normal');
      if (day.recipe.instructions) {
        const instructions = day.recipe.instructions;
        const lines = doc.splitTextToSize(instructions, 170);
        doc.text(lines, 25, yPos);
        yPos += lines.length * 4 + 5;
      }
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text(
      `Generated by Aldi Meal Planner - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  return doc;
}

/**
 * Generate Grocery List PDF
 */
export function generateGroceryListPDF(groceryList, options = {}) {
  const { weekStartDate, totalCost, budget = 100 } = options;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Grocery List', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  if (weekStartDate) {
    doc.text(`Week of ${formatWeekRange(weekStartDate)}`, pageWidth / 2, 28, { align: 'center' });
  }

  // Budget info
  doc.setFontSize(10);
  const budgetStatus = totalCost <= budget ? '✓' : '!';
  doc.text(`${budgetStatus} Total Cost: $${totalCost.toFixed(2)} / $${budget.toFixed(2)}`, 20, 40);

  // Group by category
  const categories = {
    'Produce': [],
    'Meat': [],
    'Dairy': [],
    'Pantry': [],
    'Frozen': [],
    'Bakery': []
  };

  groceryList.forEach(item => {
    const category = item.category || 'Pantry';
    if (!categories[category]) {
      categories[category] = [];
    }
    categories[category].push(item);
  });

  let yPos = 50;

  // Print each category
  Object.entries(categories).forEach(([category, items]) => {
    if (items.length === 0) return;

    // Check if we need a new page
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    // Category header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setFillColor(240, 240, 240);
    doc.rect(20, yPos - 5, 170, 8, 'F');
    doc.text(category, 22, yPos);
    yPos += 10;

    // Items
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    items.forEach(item => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }

      const checkbox = item.is_purchased ? '☑' : '☐';
      const itemName = item.ingredient_name || item.item || 'Unknown';
      const quantity = `${item.quantity_needed || item.quantity || ''} ${item.unit || ''}`.trim();
      const price = item.estimated_cost ? `$${item.estimated_cost.toFixed(2)}` : '';

      doc.text(`${checkbox}  ${itemName}`, 25, yPos);
      doc.text(quantity, 120, yPos);
      doc.text(price, 165, yPos);

      yPos += 6;
    });

    yPos += 5; // Space between categories
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text(
      `Generated by Aldi Meal Planner - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  return doc;
}

/**
 * Download PDF to user's device
 */
export function downloadPDF(doc, filename) {
  doc.save(filename);
}

/**
 * Generate and download meal plan PDF
 */
export function downloadMealPlanPDF(mealPlan, options = {}) {
  const doc = generateMealPlanPDF(mealPlan, options);
  const filename = `meal-plan-${mealPlan.weekStartDate}.pdf`;
  downloadPDF(doc, filename);
}

/**
 * Generate and download grocery list PDF
 */
export function downloadGroceryListPDF(groceryList, options = {}) {
  const doc = generateGroceryListPDF(groceryList, options);
  const filename = `grocery-list-${options.weekStartDate || 'current'}.pdf`;
  downloadPDF(doc, filename);
}
